name: Deploy to dev
on: workflow_dispatch

permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'write'

jobs:
  steps:
    - name: "install server dependcies"
      uses: "actions/setup-node@v3"
      with:
        node-version: 20
        registry-url: "https://npm.pkg.github.com"
        cache: "npm"
      run: "|
        cd server
        npm i"

    - name: "deploy"
      uses: navikt/tms-deploy/.github/workflows/mikrofrontend-deploy-v2.yaml@main
      with:
        cluster: '["dev-gcp"]'
        node-version: 20
      secrets: inherit